### ISSUE TITLE
Envoy forward proxy config

### ISSUE THREAD

**Issue by dramasamy** [vadimeisenbergibm/envoy-generic-forward-proxy#3] opened 2019-04-18 04:15 UTC
https://github.com/vadimeisenbergibm/envoy-generic-forward-proxy/blob/master/envoy_forward_proxy/envoy_config.json

Is this config implements forward proxy similar nto squid proxy? 

Example, I have 10 clients which needs to access Internet via envoy proxy. Is it possible? This can be done in squid.

In this config, what are those 8081 and 8082 ? I'd this some external proxy server?

This config looks like just a port translation

**Comment by ravikumarkgit** [comment] 2019-07-03 06:48
Hi ramasamy,
I am looking for same, are you able to configure this ?, if yes..
pls.. post me the dockercompose  file and related files.

**Comment by ravikumarkgit** [comment] 2019-07-03 06:49
> Hi Dinesh,
> I am looking for same, are you able to configure this ?, if yes..
> pls.. post me the dockercompose file and related files.

@dramasamy

**Comment by vadimeisenbergibm** [comment] 2019-07-06 08:37
Duplicate of https://github.com/vadimeisenbergibm/envoy-generic-forward-proxy/issues/2, closing this one.

**Closed as completed by vadimeisenbergibm** 2019-07-06 08:37 UTC
